#!/usr/bin/env bash

set -e

# ======================================== #

# Colors for output
NC='\033[0m'
RED='\033[0;31m'
CYAN='\033[1;36m'
GREEN='\033[0;32m'

# ======================================== #

# Usage hint in case of wrong invocation.
if [ $# -ne 1 ] ; then
    echo -e "${CYAN}[ADJUST][TEST-APP][BUILD]:${GREEN} Usage: ./build.sh [path-for-test-app] ${NC}"
    exit 1
fi

APP_PATH=$1

# ======================================== #

# Directories and paths of interest for the script.
EXAMPLE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$(dirname "$EXAMPLE_DIR")"

# ======================================== #

echo -e "${CYAN}[ADJUST][TEST-APP][BUILD]:${GREEN} Create directory on given path if it doesn't exist ... ${NC}"
mkdir -p ${APP_PATH}
echo -e "${CYAN}[ADJUST][TEST-APP][BUILD]:${GREEN} Done! ${NC}"

# ======================================== #

echo -e "${CYAN}[ADJUST][TEST-APP][BUILD]:${GREEN} Create new Cocos2d-x app ... ${NC}"
cocos new -l cpp -p com.adjust.testapp -d ${APP_PATH} AdjustTest
echo -e "${CYAN}[ADJUST][TEST-APP][BUILD]:${GREEN} Done! ${NC}"

# ======================================== #

echo -e "${CYAN}[ADJUST][TEST-APP][BUILD]:${GREEN} Remove autogenerated classes ... ${NC}"
rm -rfv ${APP_PATH}/AdjustTest/Classes/*
echo -e "${CYAN}[ADJUST][TEST-APP][BUILD]:${GREEN} Done! ${NC}"

# ======================================== #

echo -e "${CYAN}[ADJUST][TEST-APP][BUILD]:${GREEN} Use Adjust example app classes instead ... ${NC}"
cp -Rv ${EXAMPLE_DIR}/Classes/* ${APP_PATH}/AdjustTest/Classes
echo -e "${CYAN}[ADJUST][TEST-APP][BUILD]:${GREEN} Done! ${NC}"

# ======================================== #

echo -e "${CYAN}[ADJUST][TEST-APP][BUILD]:${GREEN} Script completed! ${NC}"
